### ISSUE TITLE
Add support for splitting/recombining Sega CD save files

### ISSUE THREAD

**Issue by euan-forrester** [euan-forrester/save-file-converter#155]
Currently the system can only resize the files, which at least makes them transferable between different platforms. Ideally though we'd like to be able to split apart the individual saves within the files, like we can with N64/PS1 memory card images.

All parsing of these files is apparently done by the Sega CD BIOS, and there's no documentation about how the files are laid out.

There's a tool by Krikzz that can parse these files, `savesplitter.exe`, but there's no source: https://krikzz.com/pub/support/mega-everdrive/pro-series/

I tried looking at the executable in a disassembler but the results didn't make a lot of sense to me. I think the next step here would be to step through it in a debugger.

**Comment by superctr** [comment]
I have written a program for this, maybe it will be useful: https://github.com/superctr/buram

**Comment by euan-forrester** [comment]
Oh wow, thank you -- that does look very useful! There's a lot there -- it must have been tricky to figure out!

I'll take a close look at this and incorporate it into the tool.

Thank you!

**Comment by euan-forrester** [comment]
@superctr Thank you again for all of your work creating that repo, and thank you as well for linking to it here! I've just finished adding support for Sega CD saves to the site, and you can check it out here: https://savefileconverter.com/#/sega-cd

If you're curious, you can check out my implementation here: https://github.com/euan-forrester/save-file-converter/tree/main/frontend/src/save-formats/SegaCd

Your work was awesome! I couldn't make heads or tails of these files before I saw your code, and now I understand why! Thank you!
