### ISSUE TITLE
Everdrive 64 X7 to Emulator?

### ISSUE THREAD

**Issue by PeeMoldy** [euan-forrester/save-file-converter#269]
Is there a way to convert the save files from Everdrive 64 X7 to be useable with an Emulator and then convert the save files back to be used again with ED64X7?

This is an attempt to remedy this:

https://github.com/lambertjamesd/gb64/issues/34

**Comment by euan-forrester** [comment]
Yep if you go here: https://savefileconverter.com/#/flash-carts and select N64 flash cart and Gameboy game it'll do exactly what you want. 

Feel free to hop on the discord if you run into any issues. You can find the link here: https://savefileconverter.com/#/about

**Comment by PeeMoldy** [comment]
> Yep if you go here: https://savefileconverter.com/#/flash-carts and select N64 flash cart and Gameboy game it'll do exactly what you want.
> 
> Feel free to hop on the discord if you run into any issues. You can find the link here: https://savefileconverter.com/#/about

https://www.youtube.com/watch?v=Ps--sgUQ-qo
