### ISSUE TITLE
Suport for NSO GB Save format for Spanish version of Pokémon Gen 2 games

### ISSUE THREAD

**Issue by javierhimura** [euan-forrester/save-file-converter#271]
I noticed that there are another two versions of the GB Header for save files of the Spanish Pokemon games.

In those games, the header version is HEAD-v203.0 no matter if is a Gen 1 or a Gen 2 game.
Additionally, Gen 2 games have the already known 20 additional bytes (probably related to RTC) but the same  HEAD-v203.0 version, but those games have Magic3 value set to 0x01. 

Currently, the save-file-converter is only checking Magic3 for headers with MASTER-v version, but it should do it too for games with HEAD-v version.

Currently, the conversion works for Gen 1 games but not for Gen 2 games because the conversion doesn't contemplate HEAD-v combined with Magic3 0x01

I include one example of each save file.

[saves.zip](https://github.com/euan-forrester/save-file-converter/files/14072333/saves.zip)

**Comment by euan-forrester** [comment]
Thank you for the great analysis and for the example files! That's super helpful! I'll get this fixed.

**Comment by euan-forrester** [comment]
@javierhimura This should be fixed now: just refresh your browser and please reopen if you find it's still an issue.

Thank you very much for your report!
