### ISSUE TITLE
Add support for 8bitmods Memcard Pro 1 and 2

### ISSUE THREAD

**Issue by Invictaz** [euan-forrester/save-file-converter#280]
Here are the savegames for MemcardPro 2, it supports both Playstation 1 (in .mcd format) and Playstation 2 (in .mc2 format)

Playstation 1 example .mcd file format

https://www.mediafire.com/file/tzbtey55rntyruj/MemoryCard1-1.mcd/file

Playstation 2 example .mc2 file format

https://www.mediafire.com/file/ky606fyppx0epe6/MemoryCard2-1.mc2/file

Be aware that the Playstation 2 savegames can range from 8MB to 128mb and have 8 different channels to store savegames.

**Comment by euan-forrester** [comment]
Thanks for opening this issue!

PS1 `.mcd` files are the same as the `.mcr` files supported by https://savefileconverter.com/#/ps1/emulator -- you can just rename them

For PS2 files, I have support planned for that but haven't had time yet to add it. I'd like to add support for all of the various PS2 formats found on sites like GameFAQs in addition to the raw/emulator format that you linked to.

**Comment by Invictaz** [comment]
@euan-forrester I'm not sure the MemcardPro 1 has an other save format than the MemcardPro 2 as I only have the v2.

Is the renaming the only thing you have to do since 8bitmods does quite some changes in their memorycard saving, with channels and all kinds of stuff?

**Comment by euan-forrester** [comment]
Yep the PS1 file you linked to loads fine on the site once it is renamed. I don't have a memcardpro but I would imagine it supports multiple channels and multiple games by having many files with different names on the same SD card.

For memcardrex, the link you provided there is for a different tool that runs on a PSP, made by a different author. That tool, Apollo, isn't a save file converter despite having some of that functionality, so I haven't linked to it. It's a great tool, and if it fits your needs then by all means please install it on your PSP.

Separately, the author of memcardrex has made an experimental build of that tool for MacOS, but it sounds too early to link to yet. I'll keep an eye there.

**Comment by euan-forrester** [comment]
I'm going to close this issue now, as the desired PS1 support is already there and PS2 support is planned for the future but with no specific ETA.

**Comment by Invictaz** [comment]
Actually Apollo does convert savegames. The latest release allows the .MCD format of the PS1 Memcardpro to be opened and converted. Not yet support for .MC2.
