### ISSUE TITLE
n64 extraction of multiple files request

### ISSUE THREAD

**Issue by FrostKnight** [euan-forrester/save-file-converter#322]
Can you make it so that it is possible to make .eep from controller pak saves?

That are either mpk or n64?

I am able to get that from raphnet's management tool, but I cannot extract the game I want in .eep form.

I was going to use it for this:

https://github.com/fgsfdsfgs/perfect_dark

**Comment by euan-forrester** [comment]
That should already work on the site. You just need to select the cartridge save you want once you specify the `.mpk` or `.n64` file that contains it.

**Comment by FrostKnight** [comment]
> That should already work on the site. You just need to select the cartridge save you want once you specify the `.mpk` or `.n64` file that contains it.

Very strabge, It keeps giving me the option to save as raw but nothing else.

**Comment by FrostKnight** [comment]
I suppose I could be trying to use that save on the wrong Perfect Dark version. I thought mine was 1.1, but maybe thats it? I will get back to you...

**Comment by euan-forrester** [comment]
Save as raw? Are you using the savefileconverter site? 

https://savefileconverter.com/#/n64/controller-pak should do exactly what you're looking for
